# Generated by Django 5.2 on 2025-05-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
        ('turn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='is_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='turn',
            unique_together={('barber', 'date', 'time_slot', 'is_confirmed')},
        ),
    ]
