# Generated by Django 5.1.7 on 2025-04-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='phone',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
